#!/bin/bash

#OVSROOT=/opt/openvswitch-1.9.3

#ovs-vswitchd --pidfile --detach

ovs-vsctl add-br br0
#ovs-vsctl set bridge br0 datapath_type=netdev

ovs-vsctl set-controller br0 tcp:127.0.0.1:6653 ptcp:6634:127.0.0.1
